wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 4096
embedding_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716010727
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.11.9
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
