wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716028904
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.11.9
      5: 0.17.0
      6: 4.40.2
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 4096
embedding_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.00045487509710179913
